/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class Alert extends javax.swing.JFrame {

    /**
     * Creates new form Alert
     */
    public Alert() {
        initComponents();
      
    }
    
    public Alert(String msg, String path, Color c){
        initComponents();
        setType(Type.UTILITY);
        this.setBackground(new Color(0,0,0,0));
        text.setForeground(c);
        text.setText(msg);
        iconl.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }
    
    public void fadeOut(JFrame fm){
        for (double i=1.0; i>=0.0; i=i-0.1){
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(100);
            }catch (Exception e){        
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        iconl = new javax.swing.JLabel();
        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        main.setBackground(new Color(0,0,0,150));
        main.setMaximumSize(new java.awt.Dimension(265, 80));
        main.setMinimumSize(new java.awt.Dimension(265, 80));
        main.setPreferredSize(new java.awt.Dimension(300, 80));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        main.add(iconl, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 1, -1, 80));

        text.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        text.setForeground(new java.awt.Color(33, 191, 115));
        text.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        text.setText("Message");
        main.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 1, 230, 80));

        getContentPane().add(main, new java.awt.GridBagConstraints());

        setSize(new java.awt.Dimension(323, 80));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconl;
    private javax.swing.JPanel main;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
