package main;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
/**
 *
 * @author taufik
 */
public class Login extends javax.swing.JFrame {

    public boolean a = true;
    Connection conn;
    Statement stat;
    ResultSet rs;
    String sql;
    public Login() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        conn = DB.conn;
        stat = DB.stat;
        setLayout();
    }
    
    public void setLayout(){
        this.setIconImage(new ImageIcon(getClass().getResource("/img/storeset.png")).getImage());
        this.setBackground(new Color(0,0,0,0));        
        this.setExtendedState(MAXIMIZED_BOTH);
        fullScreen(bg);
        tuser.requestFocus();
        iuser.hide();
        ipass.hide();        
    }        
    
    boolean valfield(){
        return "".equals(tuser.getText().trim())||"".equals(tpass.getText().trim());
    }
    
    private void loginAction() throws IOException{
        try{
            sql="SELECT users.username, users.password, pegawai.jabatan, pegawai.nama_pegawai, pegawai.foto FROM users JOIN pegawai ON users.kode_pegawai = pegawai.kode_pegawai where users.username='"+tuser.getText()+"' and users.password='"+tpass.getText()+"'";
            rs = stat.executeQuery(sql);
            if(rs.next()){
//                if(tuser.getText().equals(rs.getString("username"))&&tpass.getText().equals(rs.getString("password"))){
                    Alert al = new Alert("Login Success!", "/img/ok.png", new Color(33,191,115));
                    al.setVisible(true);
                    al.fadeOut(al);
                    al.setVisible(false);
                    fadeOut(this);
                    this.dispose();
                    new Dashboard(rs.getString("nama_pegawai"), rs.getString("jabatan"), rs.getBytes("foto")).setVisible(true);                                      
                }else{
                    Alert al = new Alert("Login Failed!", "/img/fail.png", new Color(255, 46, 49));
                    al.setVisible(true);
                    al.fadeOut(al);
                    al.setVisible(false);
                    tuser.setText("");
                    tpass.setText("");
                    tuser.requestFocus();
                } 
//            }
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void fadeIn(JFrame fm){
        for (double i=0.0; i<=1.0; i=i+0.1){
            String val = i + "";
            float f = Float.valueOf(val);
            fm.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch (Exception e){        
            }
        }        
    }
   
    public void fadeOut(JFrame fm){
        for (double i=1.0; i>=0.0; i=i-0.1){
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch (Exception e){        
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel();
        bgMain = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        headerLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        uluser = new javax.swing.JPanel();
        iuser = new javax.swing.JLabel();
        userPane1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ulpass = new javax.swing.JPanel();
        vis = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        ipass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        textLogin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(0, 0, 0, 100));

        bgMain.setBackground(new java.awt.Color(0, 0, 0, 0));
        bgMain.setPreferredSize(new java.awt.Dimension(0, 400));
        bgMain.setLayout(new java.awt.GridBagLayout());

        main.setBackground(new java.awt.Color(0, 0, 0, 0));
        main.setPreferredSize(new java.awt.Dimension(845, 400));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPane.setBackground(new java.awt.Color(25, 181, 254));
        loginPane.setPreferredSize(new java.awt.Dimension(425, 400));
        loginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLogin.setBackground(new java.awt.Color(25, 181, 254));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign in");

        javax.swing.GroupLayout headerLoginLayout = new javax.swing.GroupLayout(headerLogin);
        headerLogin.setLayout(headerLoginLayout);
        headerLoginLayout.setHorizontalGroup(
            headerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        headerLoginLayout.setVerticalGroup(
            headerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginPane.add(headerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 425, 40));

        userPane.setBackground(new java.awt.Color(25, 181, 254));
        userPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("username");
        userPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 6, 330, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        userPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, 30, 30));

        tuser.setBackground(new java.awt.Color(25, 181, 254));
        tuser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.setBorder(null);
        tuser.setCaretColor(new java.awt.Color(255, 255, 255));
        tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tuserKeyReleased(evt);
            }
        });
        userPane.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, 230, 30));

        uluser.setBackground(new java.awt.Color(255, 255, 255));
        uluser.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout uluserLayout = new javax.swing.GroupLayout(uluser);
        uluser.setLayout(uluserLayout);
        uluserLayout.setHorizontalGroup(
            uluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        uluserLayout.setVerticalGroup(
            uluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        userPane.add(uluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, 330, -1));

        iuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/warn.png"))); // NOI18N
        userPane.add(iuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 29, 30, 30));

        loginPane.add(userPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 425, 80));

        userPane1.setBackground(new java.awt.Color(25, 181, 254));
        userPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("password");
        userPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 6, 330, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pass.png"))); // NOI18N
        userPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, 30, 30));

        ulpass.setBackground(new java.awt.Color(255, 255, 255));
        ulpass.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout ulpassLayout = new javax.swing.GroupLayout(ulpass);
        ulpass.setLayout(ulpassLayout);
        ulpassLayout.setHorizontalGroup(
            ulpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        ulpassLayout.setVerticalGroup(
            ulpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        userPane1.add(ulpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 57, 330, -1));

        vis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invisible.png"))); // NOI18N
        vis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visMouseClicked(evt);
            }
        });
        userPane1.add(vis, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 27, 30, 30));

        tpass.setBackground(new java.awt.Color(25, 181, 254));
        tpass.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(null);
        tpass.setCaretColor(new java.awt.Color(255, 255, 255));
        tpass.setEchoChar((char)8226);
        tpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpassKeyReleased(evt);
            }
        });
        userPane1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, 230, 30));

        ipass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ipass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/warn.png"))); // NOI18N
        userPane1.add(ipass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 29, 30, 30));

        loginPane.add(userPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 425, 70));

        btnLogin.setBackground(new java.awt.Color(25, 181, 254));
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });

        textLogin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textLogin.setForeground(new java.awt.Color(255, 255, 255));
        textLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        textLogin.setText("Login");
        textLogin.setIconTextGap(8);

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        loginPane.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_w.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        loginPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 0, 30, 30));

        main.add(loginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 370));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 181, 254));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome to");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 420, 50));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/storeset.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 220, 156));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 181, 254));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ATK Store Manager");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 420, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 326, 420, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconst.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 156));

        main.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        bgMain.add(main, gridBagConstraints);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgMain, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bgMain, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void visMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visMouseClicked
if(this.a){
   tpass.setEchoChar((char)0);
   setIcon(vis, "/img/visible.png");
   this.a = false;
}else {
   tpass.setEchoChar((char)8226);
   setIcon(vis, "/img/invisible.png");
   this.a = true;    
}        
    }//GEN-LAST:event_visMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    if(valfield()){
        if("".equals(tuser.getText().trim())){
            Warn(uluser, new Color(255, 46, 49), iuser, true);
        }if("".equals(tpass.getText().trim())){
            Warn(ulpass, new Color(255, 46, 49), ipass, true);
        }
    }else{
        try {
            loginAction();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }              
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
changeUI(btnLogin, textLogin, new Color(255, 255, 255), new Color (25, 181, 254));
setIcon(textLogin, "/img/login2.png");        
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
changeUI(btnLogin, textLogin, new Color(25, 181, 254), new Color (255, 255, 255));
setIcon(textLogin, "/img/login.png");
setBorder(btnLogin, new Color(255, 255, 255), 1);        
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
changeUI(btnLogin, textLogin, new Color(6, 166, 224), new Color (255, 255, 255));
setIcon(textLogin, "/img/login.png");
setBorder(btnLogin, new Color(255, 255, 255), 1);
    }//GEN-LAST:event_btnLoginMousePressed

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
changeUI(btnLogin, textLogin, new Color(255, 255, 255), new Color (25, 181, 254));
setIcon(textLogin, "/img/login2.png");        
    }//GEN-LAST:event_btnLoginMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
fadeIn(this);
    }//GEN-LAST:event_formWindowOpened

    private void tuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuserKeyReleased
if(tuser.getText().trim().length() != 0){
    Warn(uluser, new Color(255, 255, 255), iuser, false);
}else {
    Warn(uluser, new Color(225,8,0), iuser, true);
}
    
    }//GEN-LAST:event_tuserKeyReleased

    private void tpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpassKeyReleased
if(tpass.getText().trim().length() != 0){
    Warn(ulpass, new Color(255, 255, 255), ipass, false);
}else {
    Warn(ulpass, new Color(225,8,0), ipass, true);
}        
    }//GEN-LAST:event_tpassKeyReleased

    private void tpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpassKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        if(valfield()){
            if("".equals(tuser.getText().trim())){
                Warn(uluser, new Color(255, 46, 49), iuser, true);
            }if("".equals(tpass.getText().trim())){
                Warn(ulpass, new Color(255, 46, 49), ipass, true);
            }
        }else{
            try {
                loginAction();
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     }
    }//GEN-LAST:event_tpassKeyPressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
fadeOut(this);
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());                    
                    //javax.swing.UIManager.put("TextField.caretForeground", new ColorUIResource(Color.WHITE));
                    //javax.swing.UIManager.put("PasswordField.caretForeground", new ColorUIResource(Color.WHITE));
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgMain;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel headerLogin;
    private javax.swing.JLabel ipass;
    private javax.swing.JLabel iuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPanel main;
    private javax.swing.JLabel textLogin;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    private javax.swing.JPanel ulpass;
    private javax.swing.JPanel uluser;
    private javax.swing.JPanel userPane;
    private javax.swing.JPanel userPane1;
    private javax.swing.JLabel vis;
    // End of variables declaration//GEN-END:variables

    private void fullScreen(JPanel panel){
        Dimension sz = Toolkit.getDefaultToolkit().getScreenSize();
        panel.setSize(sz.width, sz.height);
    }
    
    public void changeUI(JPanel pn, JLabel lb, Color a, Color b){
        pn.setBackground(a);
        lb.setForeground(b);
    }
    
    public void setIcon(JLabel lb, String path){
        lb.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }
    
    public void setBorder(JPanel pn, Color c, int a){
        Border border = BorderFactory.createLineBorder(c, a);
        pn.setBorder(border);
    }
    
    public void Warn(JPanel pn, Color c, JLabel lb, boolean x){
        pn.setBackground(c);
        lb.setVisible(x);
    }
 
}
